fix: spanish translation suggestions
StateOfJS/locale-es-ES pull request #5
Opened 2022-02-20 12:52 UTC by cajotafer

Hello, I see the spanish version was updated a few days ago, so I decided to contribute taking a look at it.

The changes are mostly small typos and other words updates that, I believe, match better with the context and intention of the original text.

2022-03-24 04:40 UTC, cajotafer commented
Hello, I didn't tag you before @SachaG , I think this PR was forgotten 🐣

2022-06-02 13:05 UTC, fransyrcc requested changes
Hi @cajotafer thanks for the PR, apologies it took me a while to be able to check this, would it be possible to fix the following?

2022-06-04 10:10 UTC, cajotafer commented on accounts.yml
> +      Invalid password reset token
you're right, I have removed that line

2022-06-04 10:10 UTC, cajotafer commented on common.yml
> +          También puedes ayudarnos a llegar a todo el mundo compartiendo esta encuesta. Todo ayuda cuenta. Así podremos hacer
Sure, makes sense :D

2022-06-04 10:11 UTC, cajotafer commented on results.yml
> +    t: Obtener imágen
Oh, a typo while fixing typos. Solved

2022-06-04 23:38 UTC, fransyrcc commented on results.yml
> +    t: Obtener imágen
Hola @cajotafer, can you leave `imagen` without diacritic please? Other than this small one. All looks great!

2022-06-05 11:25 UTC, cajotafer commented on results.yml
> +    t: Obtener imágen
Hi @fransyrcc yep, this has been updated in the last commit as suggested. The version you commented here is outdated.

2022-06-05 11:26 UTC, cajotafer commented on results.yml
> +    t: Obtener imagen
@fransyrcc

2022-06-05 12:59 UTC, merged